### ISSUE TITLE
Theory & Lit Review: Concept

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#1]
Concept of political discontent as lack of diffuse support--discontent with political _system_, not incumbent government
	

- our components: 
1.  external efficacy, that is, perceived government responsiveness
1. trust in politicians, parties, and parliament
1. satisfaction with parties and national office holders
1. perceptions of political corruption
- _not_ our components (things we consciously excluded): 
1. trust in other institutions 
a. government (that's specific support)
b. civil servants, courts, police, army, etc. (all apolitical, at least in theory)
1. support for "democracy" in the abstract (see https://osf.io/preprints/socarxiv/rym8g)
1. satisfaction with "democracy" in the abstract (cf. Claassen2020a,b; Claassen and Magalhaus 2022)

@Jeongho-Choi @haofengma

**Comment by fsolt** [comment]
@Jeongho-Choi, I _**really**_ like what you've done in [your review](https://github.com/fsolt/dcpo_discontent/blob/main/document/conceptualization_political_discontent.Rmd).  I have three small to tiny comments.  First, please be careful with "dimension" (e.g., at [line 22](https://github.com/fsolt/dcpo_discontent/blob/cb28fc0d61f77962b376b38b9917d494644c4ba3/document/conceptualization_political_discontent.Rmd#L22)): we don't want to suggest that the concept of discontent [is multidimensional](https://osf.io/preprints/socarxiv/rym8g), that is, that these different parts exhibit different empirical patterns in the public.  "Component" could be a better choice here.  Second, and even smaller, I like to make sure that citations in string cites are ordered temporally---that the article that was published first appears first.  Some journals want string cites in alphabetical order, but as an "S" I particularly think this is wrong.  Finally, and smallest, please consider (if you haven't already) adding a cite to @Tyhcass, I mean, [Tai et al. 2024](https://doi.org/10.1017/S0003055422000429) in [line 24](https://github.com/fsolt/dcpo_discontent/blob/cb28fc0d61f77962b376b38b9917d494644c4ba3/document/conceptualization_political_discontent.Rmd#L24). I think it is appropriate in the "mixed findings" sentence or thereabouts.

**Comment by fsolt** [comment]
Please go ahead and add it to [the paper](https://github.com/fsolt/dcpo_discontent/blob/main/paper/dcpo_discontent.qmd), @Jeongho-Choi , with one sentence per line.  (One-sentence-per-line makes it easier to identify where exactly changes were made---otherwise you end up with entire paragraphs getting highlighted in the revision history.)

**Comment by Jeongho-Choi** [comment]
Thanks! @fsolt  I fixed three things you said and added the paragraphs to the paper! As I can't render the qmd file on my local laptop for some reason unfortunately, I wasn't able to check if it looks good on paper, but the codes themselves look fine. Please let me know if there is anything I need to fix!

**Comment by fsolt** [comment]
[Jennings et al. (2017)](https://academic.oup.com/poq/article/81/3/748/3858932) should be worked in, and a slight reorientation that reflects that we'll only be using PPD as a DV and not as an IV would be helpful

**Comment by Jeongho-Choi** [comment]
> [Jennings et al. (2017)](https://academic.oup.com/poq/article/81/3/748/3858932) should be worked in, and a slight reorientation that reflects that we'll only be using PPD as a DV and not as an IV would be helpful

Thanks! I get this done soon!

**Comment by Jeongho-Choi** [comment]
I revised the paragraphs!

**Comment by fsolt** [comment]
Thanks, @Jeongho-Choi!  Closed by https://github.com/fsolt/dcpo_discontent/commit/549e5213ea6024da4409d5662d1c7cd4cc41cbd6
