### ISSUE TITLE
Theory & Lit Review: Discontent as DV

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#2]
What are the theoretical causes of public political discontent?  Empirical findings on this?  We need a couple of paragraphs to a couple of pages to set up our as-DV analysis.

**Comment by fsolt** [comment]
If there's anything beyond elections, political institutions (parliamentarian, federalism, disproportionality), and economic conditions (GDPpc, GDP growth, unemployment, and income inequality), please open a new issue to get that concept added to the dataset and our as-DV analysis.

**Comment by haofengma** [comment]
Hi Fred, upon reviewing the literature, I find that corruption appears to a source of discontent in addition to the IVs we already have. I temporarily included the discussion on corruption in my writing, but please feel free to remove it. If we decided to have it as an IV, I suggest that we might use the [V-Dem's political corruption index ](https://ourworldindata.org/grapher/political-corruption-index)as the measurement.

**Comment by fsolt** [comment]
Moved to #4 (sorry!)
