### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#4]
The front half of _**Explaining Political Dissatisfaction**_ needs a bit of theory to justify our model of the sources of PPD.  We need some discussion—a couple of paragraphs to a couple of pages, total—that hits on all of the following variables:

- [ ] Time Trend
- [ ] Election Year
- [ ] Parliamentarism
- [ ] Federalism
- [ ] Disproportionality
- [ ] GDPpc
- [ ] GDP Growth
- [ ] Unemployment
- [ ] Income Inequality

Of course, most of these _could_ be usefully grouped into larger concepts like "institutions" and "economic conditions", for example, but I'll leave the decision on whether to do something like that to you.

**Comment by Jeongho-Choi** [comment]
@fsolt  Hi Fred, I believe @haofengma has already written theories about the source of political discontent (please see political_discontent_as_dv.pdf). Just to clarify, do you want us to revise his theory section further or write separate paragraphs about them?

**Comment by haofengma** [comment]
@fsolt Hi Fred, there is currently a [version](https://github.com/fsolt/dcpo_discontent/blob/main/document/political_discontent_as_dv.pdf) of the section inside the "document" folder. Basically the variables listed here are the variables I covered in the draft, but I also have a paragraph on political corruption as the IV. I added a question regarding if we should have it inside issue 2 [here](https://github.com/fsolt/dcpo_discontent/issues/2#issuecomment-2191136455)

**Comment by fsolt** [comment]
Yes, thanks, I've just looked that over---you did an excellent job.  I'm going to suggest that we leave corruption out, for now at least.  I think perceived corruption is uncomfortably close to our concept of political discontent (we have political corruption indicators in our dataset, for example), so the argument risks being a tautological explanation.  (I mean, I almost used TI's CPI as a validation test, but I couldn't decide if it was a test of construct validation or just convergent, and ultimately I went a different way.)  So let's leave that out for now, and if reviewers want it we can reconsider.

Please plug the rest of it into the main document, https://github.com/fsolt/dcpo_discontent/blob/main/paper/dcpo_discontent.qmd, and add any needed citations to the main bib file.

**Comment by haofengma** [comment]
Thank you @fsolt ! I got the section, without corruption, incorporated!

**Comment by fsolt** [comment]
Closed by https://github.com/fsolt/dcpo_discontent/commit/74a8a277cdb87155004847199dc01a2e3968458b
