### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#5]
We need an intro that describes our research question and why it is important.  [Jennings et al. (2017)](https://academic.oup.com/poq/article/81/3/748/3858932) should provide a good starting point

**Comment by Jeongho-Choi** [comment]
As @haofengma has done most of the work on the theory, I will handle this!

**Comment by Jeongho-Choi** [comment]
I wrote the introduction! Unfortunately, I can't render the QMD file, so I can't check if it looks good on the paper. However, the code seems correct to me. I purposely did not discuss the results in the introduction yet; I will do so after the analysis is completed.

**Comment by fsolt** [comment]
I updated the pdf with [1feb707](https://github.com/fsolt/dcpo_discontent/commit/1feb707222fd889efca6bb33215595ad84f4b6ad).  And to clarify, the analysis is done, but I haven't finished describing the results.  But right, hold off while I do that---I hope to finish today

**Comment by Jeongho-Choi** [comment]
I've just finished the intro! Thanks for writing the analysis @fsolt!
