### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#8]
Our placeholder was "Political Discontent," which @haofengma smartly expanded to "Public Political Discontent" (the name of our dataset).   But what should we use as our title?

1. The simplest option would be to just keep the title short: "Public Political Discontent", and that's it.  I kind of like titles like that, personally.
2. A second option would be to build on this by stressing that we are creating new data.  
a. One option like this is "Public Political Discontent: Measuring the Decline in Diffuse Support Across Countries", which borrows from Jennings et al. (2017), "The Decline in Diffuse Support for National Politics: The Long View on Political Discontent in Britain."  I think referring to the paper that inspired us like that is valuable.  
b. Another thought along these lines is "Public Political Discontent: A Cross-National Time-Series Dataset" or something like that.
4. A third choice would be to focus more on the paper's substantive contribution: "Public Political Discontent: Trends and Sources in Cross-National Perspective".  But as the paper is written more as a 'data piece', I'm not sure that is the right way to go.
5. Other ideas?  Something that puts "Public Political Discontent" in the subtitle rather than up front?

What are your thoughts, everyone?

**Comment by haofengma** [comment]
I personally think 2a is better. The main title is simple, effectively introducing our conceptualization and the dataset's name. The subtitle conveys that the paper is about measurement, and refers to a previous study (which has been published on the same journal)

**Comment by Jeongho-Choi** [comment]
I like 2a too! That sounds like a good title!

**Comment by casstai** [comment]
I am never good at titling, but I have a slightly different idea. I lean towards the third option for the following reasons:

1. I find "Public Political Discontent: Measuring the Decline in Diffuse Support Across Countries" a bit confusing. Jennings et al. (2017) used political discontent as an indicator/ context for understanding diffuse support, therefore, they made "Diffuse Support" as their main title. In our case, we have a broader concept of public political discontent. The current title might misleadingly suggest that we are measuring diffuse support.   It may be just my understanding issue :). 

2. While the second title is more of a "data piece," I think "Trends and Sources" in the third one is still aligned with the context of our paper.

**Comment by haofengma** [comment]
> I personally think 2a is better. The main title is simple, effectively introducing our conceptualization and the dataset's name. The subtitle conveys that the paper is about measurement, and refers to a previous study (which has been published on the same journal)

I think @Tyhcass makes an important reminder that our concept of PPD is broader than diffuse support. In this case, I think title along with the 3rd option will be better. Such as "Public Political Discontent: Trends and Sources in Cross-National Perspective"

**Comment by fsolt** [comment]
["we define political discontent as dissatisfaction with or a lack of diffuse support for the political system as a whole"](https://github.com/fsolt/dcpo_discontent/blob/be0a00e159e2a07a5bebe88bf9294e34ddf630e2/paper/dcpo_discontent.qmd#L419C122-L419C241), so I'm not seeing the distinction that @Tyhcass and @haofengma are drawing.  Still, if there are objections to 'diffuse support' in 2a, we can brainstorm other options for replacing this phrase, e.g., "Public Political Discontent: Measuring Mass Political Dissatisfaction Across Countries and Over Time"

**Comment by sammo3182** [comment]
> 1. The simplest option would be to just keep the title short: "Public Political Discontent", and that's it.  I kind of like titles like that, personally.

I like this one as @fsolt but for two specific reasons: one, it is easy to memorize. And second, it increases the chance for subscribers who receive new journal issue briefs to click on the article, since they can tell we are addressing an important topic but they can't know what we'll talk about from the title only. They have to open the link and read it~ I'm thinking of making it even shorter, like "macrogrievance" or "macroresentment". Of course, I'm still influenced by Peterson et al. 2022.

If a subtitle is globally preferred for this paper, maybe "Political Discontent: ...." ahead is enough? 
For the subtitle, the "trend and source" inclines me to it as @Tyhcass and @haofengma mentioned. We are not only measuring them globally but making them comparable, right? That is, not the measurement method per se but the outcome.
In that vein,  I offer three new alternatives (the third one has nothing to do with the above. Just for fun. But we are brainstorming. Why not😜):

1. Macrogrievance
2. Political Discontent across countries over decades: Trends and determinants/sources
3. Never being satisfied: Discover political-discontent trends through a comparison across 128 countries over 44 years (Quoting the song from Hamilton, you can tell)

**Comment by haofengma** [comment]
I agree with that, as @sammo3182 mentioned, a short name is easier to remember and address an important topic. In this context, we may consider "Public Political Discontent". An even shorter name like "Macrogrievance" is also a cool idea. However, there is just an issue: adopting it may require changes to the paper's text, as we have used PPD for conceptualization.

If we still want a long name that attempts to be informative of what we have done (measurement and analysis) and what results we have found (decline), may be a title like this?

Diffuse Support Has Been in Global Decline: Insights into the Trends and Sources of Public Political Discontent from a Dynamic Comparative Dataset

**Comment by fsolt** [comment]
>  I'm thinking of making it even shorter, like "macrogrievance" or "macroresentment"

Wow, I love that idea!  Not "macrodiscontent" though?  I think that may tie best to existing lit.  Plus @haofengma is right that any of these would require some editing to the text, and "macrodiscontent" makes that job the easiest (references to the concept of political discontent, for example, can stay; only "public political discontent" and "PPD" would need the find-and-replace treatment).  The others are catchy, though.

> Diffuse Support Has Been in Global Decline: Insights into the Trends and Sources of Public Political Discontent from a Dynamic Comparative Dataset

This is good, too, I think, although definitely the complete opposite direction.  Plus I don't think we even attempt to show "global decline."  Pretty straightforward, but we'd have to do it.

Looking forward to see others' thoughts.

**Comment by haofengma** [comment]
> Plus I don't think we even attempt to show "global decline."

Considering this, "global" can be removed from this candidate title. Since "comparative" still appears in the subtitle, we can still inform readers that our evidence is not from a single country, like in the prior studies 

But, I also support the shorter title, such as "macrodiscontent" or "macroresentment". The corresponding revision of the text should be quick

**Comment by Jeongho-Choi** [comment]
I'm torn between "Public Political Discontent" and "Macrogrievance." I'm not a big fan of short titles because I kind of think they don't provide a clear sense of what the article is about, which I think a title should do. However, "Public Political Discontent" and "Macrogrievance" might convey the idea to some extent. "Macrogrievance" sounds a bit too general to me, though.

**Comment by fsolt** [comment]
> > Plus I don't think we even attempt to show "global decline."
> Considering this, "global" can be removed from this candidate title.

Sorry, my point was that we don't even attempt to show decline.  We show that within the OECD, controlling for other factors, there is a upward trend in dissatisfaction.  But we don't do a simple two-way dissatisfaction-time analysis that would show evidence of a decline in diffuse support (and point out the cases that don't fit this general story) for even those countries, let alone the full global sample.  That would be totally doable, but we haven't done it.

**Comment by fsolt** [comment]
>  I'm not a big fan of short titles because I kind of think they don't provide a clear sense of what the article is about, which I think a title should do.

This is a good point, @Jeongho-Choi.  The advantage of short titles, I think, is that they do a better job of laying claim to the topic of whatever it is you are writing about---that is, they (at least try to) work to make a paper a definitive signpost in the progress of a field, a publication that is (or at least claims to be) indispensable to any discussion of the topic.

So a title like "Macrodiscontent" is bold: it basically claims to define the topic of study.  "Public Political Discontent" is similar in claiming the topic, but less daring in that it doesn't suggest that it is *defining* the topic.  A long 'bag of words' title suggests regular science, a contribution that makes no particular claims to importance beyond exactly what the title says.  So I guess it comes down to our ambitions for the paper.

Now that I write all of that, I realize that @sammo3182 made the opposite argument to yours: that a good title intrigues the reader of the emailed ToC to click on it to get to the abstract (and then the paper), rather than spilling its conclusions so that that reader can quickly absorb them without even clicking and then delete the email.

Thanks for this discussion!  It's fun to see the different ways you all think about this.

**Comment by Jeongho-Choi** [comment]
Yes, it is a fascinating discussion!

**Comment by fsolt** [comment]
Options:
1 Macrodiscontent
2 PPD: Measuring the Decline in Diffuse Support Across Countries
3 Macrodiscontent: Measuring the Decline in Diffuse Support Across Countries

**Comment by fsolt** [comment]
Winner: Macrodiscontent Across Countries
