### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_discontent#9]
As I wrote in #7, a submission to _POQ_ should at least include citations to the source surveys, as @sammo3182 and I did in https://github.com/fsolt/dcpo_macrointerest/blob/main/paper/dcpo_macrointerest.pdf.  As Table A2 in [our current pdf](https://github.com/fsolt/dcpo_discontent/blob/main/paper/dcpo_discontent.pdf) shows, our citation coverage in https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv is incomplete, leading to blank `Citation` cells in the table.

Here's how to fix that:
1. Download the csv at https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv
2. Find each survey with a blank citation in Table A2.  You can find the data archive where the survey is housed in the `archive` column of the `surveys_data.csv` file; use the info in the `file_id` column to search for it there.  Surveys with "misc" (or "dataverse") in the `archive` column should have links in the `data_link`, `cb_link`, and/or `link` columns that should let you find them on the web.
3. Find the suggested citation and copy-and-paste it into the `citation` column.  Don't worry about formatting: of course they are all in different formats, but whatever they suggest as the citation is exactly what we use.  When there isn't a suggested citation (e.g., maybe `amb`?) use the existing cites in our file as a guide.
4. Ideally, we would be doing this all through GitHub, but we've had issues with this file in the past, so when you have filled in all of the citations, please just email me your copy of the `csv` and I'll commit your changes.

I see 145 missing citations.  @Jeongho-Choi, will you do `amb_argentina2021` to `eb903`, please?  And, @haofengma, can you please take `eb912` to `uspew209_val`?

**Comment by Jeongho-Choi** [comment]
I finished it and just emailed you with the CSV attached.
